// <auto-generated> Tensor ops duplicated onto struct Vector<T> (structs cannot inherit).
#nullable enable
using Shorokoo.Core;
using Shorokoo.Core.Nodes.NodeDefinitions;
using Shorokoo.Core.Utils;
using static Shorokoo.Globals;
namespace Shorokoo
{
    public partial struct Vector<T> where T : IVarType
    {
        /// <summary>Inserts a size-1 dimension at <paramref name="axis"/>.</summary>
        public Tensor<T> Unsqueeze(long axis)
            => OnnxOp.Unsqueeze(this, Vector(axis));

        /// <summary>Inserts size-1 dimensions at the given axes.</summary>
        public Tensor<T> Unsqueeze(Vector<int64> axes)
            => OnnxOp.Unsqueeze(this, axes);

        /// <summary>Appends a trailing size-1 dimension (axis -1).</summary>
        public Tensor<T> Unsqueeze()
            => OnnxOp.Unsqueeze(this, Vector(-1L));

        /// <summary>The shape - optionally the dims[start:end] slice of it - as an in-graph vector.</summary>
        public Vector<int64> ShapeTensor(long? start = null, long? end = null)
            // OnnxOp.Shape declares (data, end, start) — name the args; passing positionally
            // swapped start/end (e.g. ShapeTensor(1) sliced dims[:1] instead of dims[1:]).
            // The Variable→Vector<int64> operator validates the rank-1 result.
            => OnnxOp.Shape(this, end: end, start: start);

        /// <summary>The element count: the product of the dimensions, optionally restricted to dims[start:end].</summary>
        public Scalar<int64> SizeTensor(long? start = null, long? end = null)
            => this.ShapeTensor(start, end).Reduce(ReduceKind.Prod);

        /// <summary>The size of dimension <paramref name="axis"/> as a symbolic scalar.</summary>
        public Scalar<int64> DimTensor(long axis)
            => this.ShapeTensor()[axis];

        /// <summary>Gathers entries along <paramref name="axis"/> using the given indices (ONNX Gather).</summary>
        public Tensor<T> Gather(Tensor<int64> indices, long? axis)
            => OnnxOp.Gather(this, indices, axis);

        /// <summary>Matrix product with <paramref name="other"/> (ONNX MatMul).</summary>
        public Tensor<T> MatMul(Tensor<T> other)
            => OnnxOp.MatMul(this, other);

        /// <summary>Indices of the maximum values along <paramref name="axis"/>.</summary>
        public Tensor<int64> ArgMax(long axis = 0, bool keepdims = false, bool selectLastIndex = false)
            => OnnxOp.ArgMax(this, axis == 0 ? null : axis, keepdims ? null : keepdims, selectLastIndex ? selectLastIndex : null);

        /// <summary>Indices of the minimum values along <paramref name="axis"/>.</summary>
        public Tensor<int64> ArgMin(long axis = 0, bool keepdims = false, bool selectLastIndex = false)
            => OnnxOp.ArgMin(this, axis == 0 ? null : axis, keepdims ? null : keepdims, selectLastIndex ? selectLastIndex : null);

        /// <summary>Batch normalization that also returns the updated running mean and variance.</summary>
        public (Tensor<T> y, Vector<T2> runningMean, Vector<T2> runningVariance) BatchNormalizationFullOuputs<T1, T2>(Vector<T1> scale, Vector<T1> bias, Vector<T2> mean, Vector<T2> variance, float epsilon = 1e-05f, float momentum = 0.9f, bool trainingMode = false)
                where T1 : FloatLike where T2 : FloatLike
        {
            var retval = OnnxOp.BatchNormalizationFullOutputs(this, scale, bias, mean, variance, epsilon == 1e-05f ? null : epsilon, momentum == 0.9f ? null : momentum, trainingMode == false ? null : trainingMode);
            return ((Variable)retval.y, ((Tensor<T2>)retval.runningMean).Vec(), ((Tensor<T2>)retval.runningVariance).Vec());
        }

        /// <summary>Center-crops or pads to the given dimensions (ONNX CenterCropPad).</summary>
        public Tensor<T> CenterCropPad(Vector<int64> newDims, long[]? axes = null)
            => OnnxOp.CenterCropPad(this, newDims, axes);

        /// <summary>Center-crops or pads to the given dimensions (ONNX CenterCropPad).</summary>
        public Tensor<T> CenterCropPad(Vector<int32> newDims, long[]? axes = null)
            => OnnxOp.CenterCropPad(this, newDims, axes);

        /// <summary>Cumulative sum along <paramref name="axis"/>.</summary>
        public Tensor<T> CumSum<V>(Scalar<V> axis, bool exclusive = false, bool reverse = false) where V : IndexLike
            => OnnxOp.CumSum(this, axis, exclusive, reverse);

        /// <summary>Rearranges channel data into spatial blocks (ONNX DepthToSpace).</summary>
        public Tensor<T> DepthToSpace(long blockSize, DepthColumnRowMode mode = DepthColumnRowMode.DCR)
            => OnnxOp.DepthToSpace(this, blockSize, mode);

        /// <summary>Reshapes to <paramref name="newShape"/>; a 0 entry copies the corresponding input dimension unless <paramref name="allowZero"/> is true.</summary>
        public Tensor<T> Reshape(Vector<int64> newShape, bool allowZero = false)
            => OnnxOp.Reshape(this, newShape, allowZero);

        /// <summary>Permutes the dimensions; with no arguments, reverses them.</summary>
        public Tensor<T> Transpose(params long[] newDims)
            => OnnxOp.Transpose(this, newDims.Length == 0 ? null : newDims);

        /// <summary>Broadcasts to the given shape.</summary>
        public Tensor<T> Expand(params long[] shape)
            => this.Expand(Vector(shape));

        /// <summary>Broadcasts to the given shape (ONNX Expand).</summary>
        public Tensor<T> Expand(Vector<int64> shape)
            => OnnxOp.Expand(this, shape);

        /// <summary>Flattens to 2-D: dimensions before <paramref name="axis"/> collapse into the first dimension, the rest into the second.</summary>
        public Tensor<T> Flatten(long axis = 1)
            => OnnxOp.Flatten(this, axis);
    }
}
