using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Shorokoo.ModuleV2;

/// <summary>
/// Source generator for <c>[ModuleV2]</c> partial classes. It statically lowers the class's
/// static <c>Inline</c> method to MLIR-flavored assembly text (via <see cref="ModuleV2Compiler"/>,
/// which reads the method as syntax and never executes it) and emits a static
/// <c>ComputationGraph</c> property that parses that embedded text at runtime with
/// <c>MlirTextReader.Parse</c>. This is the in-compiler counterpart of the tracing path the
/// <c>[Module]</c> generator emits. See <c>src/docs/design/mlir-assembly-parser.md</c>.
/// </summary>
[Generator]
public class ModuleV2SourceGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor CompileError = new(
        id: "MV2001",
        title: "ModuleV2 Compilation Error",
        messageFormat: "Could not compile [ModuleV2] class '{0}' to MLIR: {1}",
        category: "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingInline = new(
        id: "MV2002",
        title: "ModuleV2 class needs an Inline method",
        messageFormat: "[ModuleV2] class '{0}' must declare a static 'Inline' method",
        category: "SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPotentialV2Class(node),
                transform: static (ctx, _) => GetV2ClassInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(classes, static (spc, infos) =>
        {
            foreach (var info in infos)
            {
                if (info is null) continue;

                if (info.InlineMethod is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(MissingInline, info.Location, info.ClassName));
                    continue;
                }

                string mlir;
                try
                {
                    mlir = ModuleV2Compiler.CompileMethod(info.InlineMethod);
                }
                catch (Exception e)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(CompileError, info.Location, info.ClassName, e.Message));
                    continue;
                }

                spc.AddSource($"{info.ClassName}_ModuleV2.g.cs", SourceText.From(Emit(info, mlir), Encoding.UTF8));
            }
        });
    }

    private static bool IsPotentialV2Class(SyntaxNode node)
        => node is ClassDeclarationSyntax c
           && c.Modifiers.Any(SyntaxKind.PartialKeyword)
           && c.AttributeLists.SelectMany(al => al.Attributes)
               .Any(a => a.Name.ToString() is "ModuleV2" or "ModuleV2Attribute");

    private static V2ClassInfo? GetV2ClassInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        // Confirm the attribute semantically (the syntactic predicate is only a fast pre-filter).
        if (!symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "ModuleV2Attribute"))
            return null;

        var inline = classDecl.Members
            .OfType<MethodDeclarationSyntax>()
            .FirstOrDefault(m => m.Identifier.Text == "Inline" && m.Modifiers.Any(SyntaxKind.StaticKeyword));

        var ns = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();
        return new V2ClassInfo(symbol.Name, ns, classDecl.Modifiers.Any(SyntaxKind.StaticKeyword), inline, classDecl.GetLocation());
    }

    private static string Emit(V2ClassInfo info, string mlir)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n");
        if (info.Namespace is not null)
            sb.Append("namespace ").Append(info.Namespace).Append("\n{\n");

        var staticMod = info.IsStatic ? "static " : "";
        sb.Append("    [global::System.Runtime.CompilerServices.CompilerGenerated]\n");
        sb.Append("    public ").Append(staticMod).Append("partial class ").Append(info.ClassName).Append("\n    {\n");
        sb.Append("        private const string __ModuleV2Mlir = ").Append(Literal(mlir)).Append(";\n");
        sb.Append("        private static global::Shorokoo.Graph.FastComputationGraph? __moduleV2Template;\n");
        sb.Append("        /// <summary>The statically-compiled computation graph, parsed from embedded MLIR text.</summary>\n");
        sb.Append("        public static global::Shorokoo.Graph.FastComputationGraph ComputationGraph\n");
        sb.Append("            => (__moduleV2Template ??= global::Shorokoo.Core.Factory.Mlir.MlirTextReader.Parse(__ModuleV2Mlir)).Clone();\n");
        sb.Append("    }\n");

        if (info.Namespace is not null)
            sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>Renders <paramref name="s"/> as a C# double-quoted string literal.</summary>
    private static string Literal(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        sb.Append('"');
        foreach (var c in s)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private sealed class V2ClassInfo
    {
        public string ClassName { get; }
        public string? Namespace { get; }
        public bool IsStatic { get; }
        public MethodDeclarationSyntax? InlineMethod { get; }
        public Location Location { get; }

        public V2ClassInfo(string className, string? ns, bool isStatic, MethodDeclarationSyntax? inline, Location location)
        {
            ClassName = className;
            Namespace = ns;
            IsStatic = isStatic;
            InlineMethod = inline;
            Location = location;
        }
    }
}
